/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.garodriguezlp.cracking.coding.interview.one.one;

import java.util.HashSet;
import java.util.Set;

public class IsUnique {

    public static void main(String[] args) {
         IsUnique isUnique = new IsUnique();
        System.out.println("Is unique tests");
        System.out.println("Has 'abcde' just unique chars?: " + isUnique.test("abcde"));
        System.out.println("Has 'aabcde' just unique chars?: " + isUnique.test("aabcde"));
    }

    private boolean test(String testingString) {
        char[] characters = testingString.toCharArray();
        Set<Character> unique = new HashSet<>();
        for (char character : characters) {
            if(unique.contains(character)){
                return false;
            }            
            unique.add(character);
        }
        return true;
    }
}
