/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.garodriguezlp.cracking.coding.interview.one.one;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        IsUnique classUnderTest = new IsUnique();
    }
}
